---
#
# Ansible managed
#
repository:
  description: Install oracle_instant_client on your system.
  homepage: https://robertdebock.nl/
  topics: oracleinstantclient, application, database, linux, system, tools, ansible, molecule, playbook
